services:
  - type: web
    name: cabinet-medical-clean
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader && npm install && npm run build
    startCommand: php artisan migrate --force && php artisan db:seed --class=RoleSeeder --force && php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
